version: '3.4'
services:

  back:
    restart: unless-stopped
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - '/scripts/entrypoint.dev.sh'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=localhost
    ports:
      - 8080:8080

  web:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      DOLLAR: '$$'
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:80

networks:
  default:
    driver: bridge
